### ISSUE TITLE
Rename "master" branch to "main"

### ISSUE THREAD

**Issue by bearloga** [wikimedia-research/wiki-segmentation#7]
Part of [T254646](https://phabricator.wikimedia.org/T254646)

**Comment by nshahquinn** [comment]
Maybe we should write a script to do this for all the repos in this org? Most of them will never be used again, but it's still nice to be thorough. We'd have to contact the research community so people don't get confused, but it would probably still be more efficient than doing them one-by-one.

**Comment by nshahquinn** [comment]
Well, hey! Look at this old thing. I just changed it to "main".
